<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- Bootstrap CSS -->
      <!-- build:css css/main.css -->
      <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
      
      <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">
      <link rel="stylesheet" href="node_modules/gridjs/dist/theme/mermaid.min.css">
      <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
      <link rel="stylesheet" href="css/styles.css">
      <script src="node_modules/jquery/dist/jquery.min.js"></script>
      <!-- end build -->
  <title><?=$title?></title>
</head>

   
<body>
  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="index.php">Cabinet Chebbi</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="index.php">Accueil </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="add.php">Ajouter Patient</a>
        </li>
    </ul>
  </div>
  </nav>
  <div class="jumbotron jumbotron-fluid px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Cabinet Chebbi
    </h1>
  </div>
  
   <?php include $template . '.phtml'; ?>
  
</body>


<script src="node_modules/gridjs-jquery/dist/gridjs.production.min.js"></script>
<script src="js/grid-table.js"></script>

 <script src="node_modules/popper.js/dist/umd/popper.min.js"></script>
 <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</html>
